name: Download data
on: push # temporary, for testing this script
jobs:
  download-data:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: download most recent data
        run: rm ./public/stats-history.json
        run: node ./utils/downloadData.mjs
      
      - name: check git diff
        run: git diff